name: BanTools
version: 1.0.0
api: [3.0.0]
author: BEcraft Gameplay
main: Tool\Main
commands:
 invisible:
  description: Make you a ghost
  default: op
 visible:
  description: Make you visible to players
  default: op
 eb:
  description: Make you visible to players
  default: op
 ep:
  description: Pardon any which is banned
  default: op
 info:
  description: See any player information
  default: op
 fre:
  description: Freeze and unFreeze any player
  default: op
 co:
  description: Chat just for op
  default: op
 tools:
  description: Check all commands
  default: op
 eblist:
  description: Check all banned players from your server
  default: op
 bancheck:
  description: Check info about any banned player
  default: op
